version: "3"

services:

  ollama:
    image: ollama/ollama:latest
    #restart: always
    #restart: unless-stopped
    volumes:
      - ${OLLAMA_DATA_VOLUME_PATH}:/root/.ollama 
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: 1

